: TRIPLE DUP DUP + + ;
: POW2 DUP 0 = IF DROP DROP 1 . EXIT THEN DUP 1 = IF DROP . EXIT THEN 1 PICK SWAP 1 - 0 DO 1 PICK * LOOP SWAP DROP . ;
: TEST-CASE   CASE  1 OF  ." UN " CR  ENDOF 2 OF  ." DEUX " CR ENDOF 3 OF  ." TROIS "  CR ENDOF ." Others " CR  ENDCASE ;
: FACTLOOP 1 + DUP 0 = IF DROP 1 EXIT THEN DUP 1 = IF DROP 1 EXIT THEN 1 SWAP 1 DO I * LOOP ;
: HELLO  ." Hello " USERNAME @ PRINT ."  How are uou ? " CR ;
: MACRON  ." Macron est un saint homme ! " CR ;
(               : TEST-DELAY  COUNT ! BEGIN ." Hello " CR 1000 DELAY COUNT @ 1 - DUP COUNT ! 0 = UNTIL ; )
: CREDIT ." Brought  to you by Cleobuline https://github.com/cleobuline/forth-bot-gmp-irc-threaded-multi-users/tree/main Site https://labynet.fr " CR  ;
VARIABLE START-TIME
: SET-START MICRO START-TIME ! ;
: TIME-SINCE MICRO START-TIME @ - ;
: SHOW-TIME TIME-SINCE . ;
 : 2DUP OVER OVER ;
 :  3DUP 
  2 PICK 2 PICK 2 
   PICK ; 
 : PRIME-FACTORS  
  DUP 1 = IF DROP EXIT THEN
  >R 2
  BEGIN
    R@ 1 >
  WHILE
    DUP DUP * R@ > IF
      R@ NUM-TO-STR 32 EMIT
      R> DROP 1 >R
    ELSE
      R@ OVER MOD 0 = IF
        DUP NUM-TO-STR 32 EMIT
        R@ OVER / R> DROP >R
      ELSE
        1 +
      THEN
    THEN
  REPEAT
  DROP R> DROP CR ;
 
 : SHOW-PRIMES 0  DO   I PRIME? IF I NUM-TO-STR  32 EMIT  THEN  LOOP CR  ;  
 


 
 

: TABLE-MULT ( n -- )
  DUP CR 1 + 1 DO
    DUP 1 + 1 DO
      I J * DUP DUP 100 < IF 32 EMIT THEN DUP 10 < IF 32 EMIT THEN NUM-TO-STR 32 EMIT DROP
    LOOP
    124 EMIT CR
  LOOP DROP ;
  : TABLE DUP CR 1 + 1 DO DUP 1 + 1 DO I J * NUM-TO-STR 32 EMIT LOOP 124 EMIT CR LOOP DROP ;
  
 
  VARIABLE OFF
  VARIABLE DAYS 
VARIABLE YEAR 
VARIABLE MONTH 
VARIABLE DAY

: LEAP-YEAR? DUP 4 MOD 0 = IF DUP 100 MOD 0 = IF 400 MOD 0 = EXIT THEN DROP 1 EXIT THEN DROP 0 ;

: MONTH-NAME ( n -- )
  DUP 1 = IF   ." January" EXIT THEN
  DUP 2 = IF   ." February" EXIT THEN
  DUP 3 = IF   ." March" EXIT THEN
  DUP 4 = IF   ." April" EXIT THEN
  DUP 5 = IF   ." May" EXIT THEN
  DUP 6 = IF   ." June" EXIT THEN
  DUP 7 = IF   ." July" EXIT THEN
  DUP 8 = IF   ." August" EXIT THEN
  DUP 9 = IF   ." September" EXIT THEN
  DUP 10 = IF   ." October" EXIT THEN
  DUP 11 = IF   ." November" EXIT THEN
  DUP 12 = IF   ." December" EXIT THEN
   DROP  ." Unknown" ;

: DAYS-IN-MONTH ( month year -- days )
  OVER 2 = IF LEAP-YEAR? IF 29 ELSE 28 THEN EXIT THEN
  OVER 4 = IF DROP 30 EXIT THEN
  OVER 6 = IF DROP 30 EXIT THEN
  OVER 9 = IF DROP 30 EXIT THEN
  OVER 11 = IF DROP 30 EXIT THEN
  DROP DROP 31 ;
  
: ZELLER ( month year -- day )
  >R
  DUP 3 < IF
    12 + R> 1 - >R
  THEN
  R@ 100 MOD
  R@ 100 /
  SWAP
  DUP 4 / +
  SWAP
  2 * 0 SWAP - +
  SWAP
  1 + 13 * 5 /
  1 +
  +
  R> 100 / 4 / +
  6 + ( Décalage de -1 jour )
  7 MOD
 
;
: 2SWAP ( x1 x2 x3 x4 -- x3 x4 x1 x2 )
  ROT >R ROT R> ;
: SPACES ( n -- )
  0 DO 32 EMIT LOOP ;
  
: SPACES ( N -- ) 0 DO 32 EMIT LOOP ;

 : PRINT-ASCII 126 32 1 + DO I NUM-TO-STR  32 EMIT  I EMIT 44 EMIT LOOP CR  ;  
 :  MULTI-CHAR 0 DO DUP EMIT LOOP CR  DROP ;

: NIP ( a b -- b )
  SWAP DROP ;
  
 : MAX ( n1 n2 -- n )
  2DUP > IF DROP ELSE SWAP DROP THEN ;




: CAL ( day  month year -- )
  2DUP
  SWAP MONTH-NAME DROP
  32 EMIT NUM-TO-STR CR
  ." Mo Tu We Th Fr Sa Su" CR

  2DUP ZELLER   
  DUP 0 = IF DROP 6 ELSE 1 - THEN DUP OFF !
   

  OFF @ 0 > IF   
    OFF @ 0 DO 32 EMIT 32 EMIT  32 EMIT  LOOP
  THEN

  DROP 2DUP 
  2DUP DAYS-IN-MONTH 1 +  
  1 DO
    I 10 < IF 32 EMIT 32 EMIT ELSE 32 EMIT THEN
    I NUM-TO-STR
    OFF @ I + 7 MOD 0 = IF CR THEN
  LOOP

  2DROP CR ;
  
 
: >= ( A B -- FLAG ) < NOT ;
: 0> ( n -- flag ) DUP 0 = IF DROP 0 EXIT THEN DUP 0 < IF DROP 0 EXIT THEN DROP 1 ;
: <= ( A B -- FLAG ) SWAP < NOT ;
 
: DAYS-IN-YEAR ( YEAR -- N )
  DUP LEAP-YEAR? IF 366 ELSE 365 THEN ;

 VARIABLE TODAY-DAY
 : CALC-YEARS 1970 YEAR ! BEGIN DAYS @ 0> WHILE YEAR @ 4 MOD 0 = IF 366 ELSE 365 THEN DUP DAYS @ >= NOT IF DAYS @ SWAP - DAYS ! YEAR @ 1 + YEAR ! ELSE DROP EXIT THEN REPEAT DROP ;
: CALC-MONTHS 1 MONTH ! BEGIN DAYS @ 0> WHILE MONTH @ 2 = IF 28 ELSE MONTH @ 4 = IF 30 ELSE MONTH @ 6 = IF 30 ELSE MONTH @ 9 = IF 30 ELSE MONTH @ 11 = IF 30 ELSE 31 THEN THEN THEN THEN THEN DUP DAYS @ >= NOT IF DAYS @ SWAP - DAYS ! MONTH @ 1 + MONTH ! ELSE DROP EXIT THEN REPEAT DROP ;
: CALC-DAY DAYS @ 1 + DAY ! ;
: TODAY MILLI 1000 / 86400 / DAYS ! CALC-YEARS CALC-MONTHS CALC-DAY DAY @ MONTH @ YEAR @ ;

: CAL-IRC-HIGHLIGHT  
  2 PICK TODAY-DAY ! 2DUP SWAP MONTH-NAME DROP 32 EMIT NUM-TO-STR CR
  ." Mo Tu We Th Fr Sa Su" CR
  2DUP ZELLER DUP 0 = IF DROP 6 ELSE 1 - THEN DUP OFF !
  OFF @ 0 > IF OFF @ 0 DO 32 EMIT 32 EMIT 32 EMIT LOOP THEN
  DROP 2DUP 2DUP DAYS-IN-MONTH 1 + 1 DO
    I 10 < IF 32 EMIT 32 EMIT ELSE 32 EMIT THEN
    I TODAY-DAY @ = IF 22 EMIT I NUM-TO-STR 15 EMIT ELSE I NUM-TO-STR THEN
    OFF @ I + 7 MOD 0 = IF CR THEN
  LOOP
  2DROP 2DROP 2DROP CR ;
: TODAY-CAL-IRC TODAY CAL-IRC-HIGHLIGHT ;
 



